# Generated by Django 5.0.3 on 2024-03-14 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_day', models.DateField()),
                ('salary', models.CharField(max_length=255)),
                ('marital_situation', models.CharField(choices=[('married', 'married'), ('divorced', 'divorced'), ('single', 'single'), ('widow', 'widow')], max_length=100)),
                ('sexe', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100)),
                ('rip', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_num', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('president', 'President of the Committee'), ('vice_president', 'Vice President of the Committee'), ('treasurer', 'Treasurer of the Committee'), ('member', 'Member of the Committee'), ('employee', 'Employee')], max_length=100)),
                ('phone_number', models.CharField(max_length=255)),
                ('is_created', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('requests', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
