# Generated by Django 5.0.3 on 2024-03-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employee_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_admin',
        ),
    ]
