# Generated by Django 5.0.3 on 2024-03-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employee_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_admin',
        ),
    ]
