# Generated by Django 5.0.3 on 2024-03-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_employee_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bank_num',
            new_name='bank_rib',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='birth_day',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='marital_situation',
            new_name='martial_situation',
        ),
    ]
