# Generated by Django 5.0.3 on 2024-03-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_bank_num_employee_bank_rib_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bank_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
