# Generated by Django 5.0.3 on 2024-03-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_employee_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_created',
        ),
    ]
