# Generated by Django 5.0.3 on 2024-03-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_employee_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_adress',
            field=models.CharField(default='skikda', max_length=255),
            preserve_default=False,
        ),
    ]
