# Generated by Django 5.0.3 on 2024-03-14 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_employee_birth_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(default='helo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default='hooy', max_length=255),
            preserve_default=False,
        ),
    ]
