# Generated by Django 5.0.3 on 2024-03-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_request_created_at_request_description_request_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='requests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.request'),
        ),
    ]
