# Generated by Django 5.0.3 on 2024-03-15 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_employee_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='requests',
        ),
        migrations.RemoveField(
            model_name='request',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='request',
            name='description',
        ),
        migrations.RemoveField(
            model_name='request',
            name='name',
        ),
        migrations.AddField(
            model_name='request',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
