# Generated by Django 5.0.3 on 2024-03-26 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='recruted_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
