# Generated by Django 5.0.3 on 2024-03-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_employee_recruted_at_employee_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='retired_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
