# Generated by Django 5.0.3 on 2024-06-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_employee_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
