# Generated by Django 5.0.3 on 2024-06-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_employee_is_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_created',
        ),
    ]
