# Generated by Django 5.0.3 on 2024-05-01 10:42

import backend.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_remove_meeting_period_remove_meeting_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='pv',
            field=models.FileField(null=True, upload_to=backend.utils.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
    ]
