# Generated by Django 5.0.3 on 2024-05-13 09:27

import backend.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_alter_meeting_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='pv',
            field=models.FileField(blank=True, null=True, upload_to=backend.utils.get_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
    ]
