# Generated by Django 5.0.3 on 2024-06-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_canceled_meeting_link_alter_meeting_pv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
