# Generated by Django 5.0.3 on 2024-03-17 19:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_aid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_created_at', models.DateField(auto_now_add=True)),
                ('financial_aid_type', models.CharField(choices=[('dece', 'dece'), ('naissance_bebe', "naissance d'un bébé"), ('mariage', 'mariage')], max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.CharField(max_length=10)),
                ('loan_motivation', models.TextField()),
                ('payment_method', models.TextField(choices=[('ccp', 'ccp'), ('banque', 'banque')])),
                ('loan_status', models.CharField(choices=[('waiting', 'En attente'), ('refused', 'Rejeté'), ('approved', 'Approuvé'), ('finished', 'terminé')], max_length=30)),
                ('start_loan_date', models.DateField(null=True)),
                ('loan_period', models.DurationField(default=datetime.timedelta(days=365))),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='%Y/%m/%d')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('financial_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.financial_aid')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.loan')),
            ],
        ),
    ]
