# Generated by Django 5.0.3 on 2024-03-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_remove_document_loan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_aid',
            name='family_member_death',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financial_aid',
            name='financial_aid_status',
            field=models.CharField(choices=[('waiting', 'en attente'), ('refused', 'refusé'), ('approved', 'approuvé')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financial_aid',
            name='request_response_at',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='request_created_at',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(upload_to='docs/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='financial_aid',
            name='financial_aid_type',
            field=models.CharField(choices=[('family_member_death', "décès d'un membre de famille"), ('employee_death', "décès d'un employé"), ('child_birth', "naissance d'un fils"), ('mariage', 'mariage')], max_length=255),
        ),
    ]
