# Generated by Django 5.0.3 on 2024-03-19 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_financial_aid_family_member_death_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='financial_aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.financial_aid'),
        ),
    ]
