# Generated by Django 5.0.3 on 2024-03-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_document_financial_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_aid',
            name='request_response_at',
            field=models.DateField(null=True),
        ),
    ]
