# Generated by Django 5.0.3 on 2024-03-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_remove_financial_aid_family_member_death_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_aid',
            name='financial_aid_type',
            field=models.CharField(choices=[('family_member_death', "décès d'un membre de famille"), ('employee_death', "décès d'un employé"), ('child_birth', "naissance d'un fils"), ('mariage', 'mariage')], max_length=50),
        ),
    ]
