# Generated by Django 5.0.3 on 2024-03-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_alter_financial_aid_financial_aid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_period',
            field=models.IntegerField(max_length=2),
        ),
    ]
