# Generated by Django 5.0.3 on 2024-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_alter_loan_loan_amount_alter_loan_loan_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_period',
            field=models.IntegerField(),
        ),
    ]
