# Generated by Django 5.0.3 on 2024-03-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_alter_loan_loan_amount_alter_loan_loan_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial_aid',
            name='financial_aid_amount',
        ),
        migrations.AlterField(
            model_name='financial_aid',
            name='family_member',
            field=models.CharField(blank=True, choices=[('wife', 'epouse'), ('son', 'fils'), ('parent', 'parent')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financial_aid',
            name='financial_aid_status',
            field=models.CharField(choices=[('draft', 'brouillon'), ('waiting', 'en attente'), ('refused', 'refusé'), ('approved', 'approuvé')], max_length=50),
        ),
        migrations.AlterField(
            model_name='financial_aid',
            name='financial_aid_type',
            field=models.CharField(choices=[('family_member_death', "décès d'un membre de famille"), ('employee_death', "décès d'un employé"), ('child_birth', "naissance d'un fils"), ('mariage', 'mariage'), ('circumcision_newborn', "Circoncision d'un nouveau-né"), ('retirement_financial_aid', 'Aide financière à la retraite'), ('surgeries', 'les opérations chirurgicales'), ('mineral_baths', 'Bains minéraux'), ('accident_and_disasters', "Assistance en cas d'accident Et les catastrophes"), ('social_and_health_aid', 'Aide aux conditions sociales et sanitaires')], max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('draft', 'brouillon'), ('waiting', 'En attente'), ('refused', 'Rejeté'), ('approved', 'Approuvé'), ('finished', 'terminé')], max_length=30),
        ),
    ]
