# Generated by Django 5.0.3 on 2024-03-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_remove_financial_aid_financial_aid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_aid',
            name='request_response_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
