# Generated by Django 5.0.3 on 2024-03-27 04:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_alter_financial_aid_request_response_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_uploaded_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='random_name',
            field=models.CharField(default='somerandomname', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='financial_aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='requests.financial_aid'),
        ),
    ]
