# Generated by Django 5.0.3 on 2024-03-27 05:24

import backend.utils as utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "requests",
            "0013_document_document_uploaded_at_document_random_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_file",
            field=models.FileField(upload_to=utility.get_path),
        ),
    ]
