# Generated by Django 5.0.3 on 2024-03-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0014_alter_document_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.FloatField(),
        ),
    ]
