# Generated by Django 5.0.3 on 2024-03-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0015_document_loan_alter_document_financial_aid'),
        ('requests', '0016_alter_loan_start_loan_date'),
    ]

    operations = [
    ]
