# Generated by Django 5.0.3 on 2024-03-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0017_merge_20240327_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='random_name',
        ),
    ]
