# Generated by Django 5.0.3 on 2024-03-28 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0018_remove_document_random_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='requests.loan'),
        ),
    ]
