# Generated by Django 5.0.3 on 2024-03-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0019_alter_document_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_size',
            field=models.FloatField(default=10.05),
        ),
    ]
