# Generated by Django 5.0.3 on 2024-03-31 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0017_merge_20240328_0406'),
        ('requests', '0020_document_document_size'),
    ]

    operations = [
    ]
