# Generated by Django 5.0.3 on 2024-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0021_merge_20240330_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='start_loan_date',
            new_name='request_response_at',
        ),
        migrations.AlterField(
            model_name='financial_aid',
            name='request_created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='request_created_at',
            field=models.DateField(null=True),
        ),
    ]
