# Generated by Django 5.0.3 on 2024-04-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0022_rename_start_loan_date_loan_request_response_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=4, max_digits=50),
        ),
    ]
