# Generated by Django 5.0.3 on 2024-04-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0023_alter_loan_loan_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='financial_aid',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=50, null=True),
        ),
    ]
