# Generated by Django 5.0.3 on 2024-05-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0025_alter_financial_aid_amount_alter_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
