# Generated by Django 5.0.3 on 2024-05-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0026_loan_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_aid',
            name='financial_aid_status',
            field=models.CharField(choices=[('draft', 'brouillon'), ('waiting', 'en attente'), ('refused', 'refusé'), ('approved', 'approuvé'), ('finished', 'terminé')], max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('draft', 'brouillon'), ('waiting', 'En attente'), ('refused', 'Rejeté'), ('approved', 'Approuvé'), ('payment_started', 'En cours de paiement'), ('finished', 'terminé')], max_length=30),
        ),
    ]
