# Generated by Django 5.0.3 on 2024-03-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=35)),
        ),
    ]
