# Generated by Django 5.0.3 on 2024-03-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0004_alter_offre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='slug',
        ),
    ]
