# Generated by Django 5.0.3 on 2024-03-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenceIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expence', 'expence'), ('income', 'income')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tag', models.CharField(max_length=50)),
                ('motif', models.TextField()),
            ],
        ),
    ]
