# Generated by Django 5.0.3 on 2024-04-06 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_management', '0002_alter_expenceincome_type'),
        ('requests', '0022_rename_start_loan_date_loan_request_response_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenceincome',
            name='tag',
        ),
        migrations.AddField(
            model_name='expenceincome',
            name='financial_aid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='requests.financial_aid'),
        ),
        migrations.AddField(
            model_name='expenceincome',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='requests.loan'),
        ),
        migrations.AlterField(
            model_name='expenceincome',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
