# Generated by Django 5.0.3 on 2024-04-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_management', '0004_rename_expenceincome_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
