# Generated by Django 5.0.3 on 2024-04-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_management', '0005_record_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_balance', models.DecimalField(decimal_places=4, default=0, max_digits=1000)),
                ('current_year_expenses', models.DecimalField(decimal_places=4, default=0, max_digits=1000)),
                ('current_year_income', models.DecimalField(decimal_places=4, default=0, max_digits=1000)),
            ],
        ),
    ]
