# Generated by Django 5.0.3 on 2024-04-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_management', '0007_commity_current_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commity',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='commity',
            name='current_year_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='commity',
            name='current_year_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
