# Generated by Django 5.0.3 on 2024-05-05 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_management', '0009_alter_record_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 5, 21, 38, 0, 54404, tzinfo=datetime.timezone.utc)),
        ),
    ]
