# Generated by Django 5.0.3 on 2024-05-05 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_management', '0010_alter_record_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
